import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import ConditionalHeader from "./components/ConditionalHeader";
import "./globals.css";

const ubuntu = Ubuntu({
  weight: "300",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cash Flipper",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ubuntu.className} antialiased`}>
        <main className="flex justify-center items-center gap-[20px] flex-col w-full max-w-6xl mx-auto px-5">
          <ConditionalHeader />
          {children}
        </main>
      </body>
    </html>
  );
}
