import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import Header from "./components/header/Header";
import "./globals.css";

const ubuntu = Ubuntu({
  weight: "300",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cash Flipper",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ubuntu.className} antialiased`}>
        <main className="w-[1180px] ml-[20px] mr-[20px]">
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
